FROM node:12.2

ENV HOME=/home/app

RUN apt-get update && apt-get install htop

COPY package.json package-lock.json index.js config.js $HOME/node_docker/

WORKDIR $HOME/node_docker

RUN npm install --silent --progress=false

COPY . $HOME/node_docker

EXPOSE 8080

CMD ["/bin/bash", "-c", "npm ci; npm start"]